import type { NextPage } from 'next';
import Head from 'next/head';
import FooterInfo from '../components/footerInfo/FooterInfo';
import Article from '../components/article/Article';
import styles from '../styles/Home.module.css';
import { useContext } from 'react';
import { AuthContext } from '../context';

const Home: NextPage = () => {
  const { menuTurnedOff } = useContext(AuthContext);

  return (
    <div
      className={[styles.container, !menuTurnedOff ? styles.shadow : null].join(
        ' '
      )}
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Article />
      </main>

      <footer className={styles.footer}>
        <FooterInfo />
      </footer>
    </div>
  );
};

export default Home;
