import type { NextPage } from 'next';
import React, { useState } from 'react';
import Head from 'next/head';
import Header from '../components/header/Header';
import Article from '../components/article/Article';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const [sideMeniuOpen, setSideMeniuOpen] = useState(false);

  return (
    <div
      className={[styles.container, !sideMeniuOpen ? styles.shadow : ' '].join(
        ' '
      )}
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header
        sideMeniuOpen={sideMeniuOpen}
        setSideMeniuOpen={setSideMeniuOpen}
      />
      <main className={styles.main}>
        <Article />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
